<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('students', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained('schools')->restrictOnDelete();

            // Identity
            $table->string('full_name', 200);
            $table->string('father_name', 200);
            $table->string('cnic', 15)->nullable();          // 13-digit Pakistani CNIC (no dashes stored)
            $table->string('b_form', 15)->nullable();        // For minors: B-Form number
            $table->date('date_of_birth')->nullable();
            $table->enum('gender', ['male', 'female']);
            $table->string('nationality', 50)->default('Pakistani');
            $table->string('religion', 50)->nullable();

            // Contact
            $table->string('phone', 20)->nullable();
            $table->string('guardian_phone', 20)->nullable();
            $table->string('address', 500)->nullable();

            // Photo
            $table->string('photo_path', 500)->nullable();

            // Official enrollment number — NULL until challan is confirmed by Super Admin
            // Generated by PostgreSQL sequence, never by application code
            $table->string('enrollment_number', 20)->nullable()->unique();
            $table->timestamp('enrollment_number_issued_at')->nullable();

            // Status flags
            $table->boolean('is_active')->default(true);
            $table->boolean('is_expired')->default(false);  // 2 consecutive years no activity
            $table->timestamp('expired_at')->nullable();

            $table->timestamps();
            $table->softDeletes();  // Records never truly deleted — only soft-deleted for admin cleanup

            $table->index(['school_id', 'is_active']);
            $table->index('enrollment_number');
            $table->index(['school_id', 'enrollment_number']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('students');
    }
};
