<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('challans', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained('schools')->restrictOnDelete();
            $table->foreignId('academic_year_id')->constrained('academic_years')->restrictOnDelete();

            // Enrollment and examination are ALWAYS separate challans
            $table->enum('challan_type', ['enrollment', 'examination']);

            // Challan number: human-readable reference (generated by system, not by sequence)
            $table->string('challan_number', 30)->unique();

            // Payment info
            $table->unsignedBigInteger('total_amount_paisas');  // Sum of all student fees
            $table->unsignedInteger('student_count');

            // Status lifecycle: draft → submitted → confirmed | rejected
            $table->enum('status', ['draft', 'submitted', 'confirmed', 'rejected'])->default('draft');

            // Submission
            $table->timestamp('submitted_at')->nullable();
            $table->string('bank_name', 100)->nullable();
            $table->string('bank_branch', 150)->nullable();
            $table->string('bank_reference', 100)->nullable();  // Bank transaction ref
            $table->date('payment_date')->nullable();
            $table->string('deposit_slip_path', 500)->nullable();  // Scanned copy upload

            // Board approval
            $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('approved_at')->nullable();
            $table->text('rejection_reason')->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['school_id', 'academic_year_id', 'challan_type']);
            $table->index(['status', 'academic_year_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('challans');
    }
};
